language: android
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.0
  - android-28
before_install:
- openssl aes-256-cbc -K $encrypted_f2da1cf98853_key -iv $encrypted_f2da1cf98853_iv
  -in Mugger.jks.enc -out Mugger.jks -d
- yes | sdkmanager "platforms;android-28"
- chmod +x gradlew
before_script:
script:
- "./gradlew build"
jdk:
- oraclejdk8