language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.0
    - android-28
	- sys-img-armeabi-v7a-android-23
before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew
 before_script:
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
script:
   - ./gradlew build connectedCheck
jdk:
  - oraclejdk8